### ISSUE TITLE
Textfabric identifier

### ISSUE THREAD

**Issue by inge1211** [CLARIAH/ineo-content#5]
@JanessaMay Is het mogelijk om de identifiers van de tool textfabric (https://github.com/CLARIAH/ineo-content/blob/master/src/tools/text-fabric.md) hetzelfde te maken als in de codemeta: https://tools.clariah.nl/files/textfabric.codemeta.json

Dan wordt de juiste content aan de juiste metadata gekoppeld. 

dus identifier: text-fabric wordt 
identifier: textfabric

**Comment by JanessaMay** [comment]
Gefixt
