### ISSUE TITLE
Error in YAML

### ISSUE THREAD

**Issue by inge1211** [CLARIAH/ineo-content#9]
Er is een "Error in user YAML: (<unknown>): mapping values are not allowed in this context at line 1 column 14" bij [ewald](https://github.com/CLARIAH/ineo-content/blob/master/src/tools/ewald.md), [ewbd](https://github.com/CLARIAH/ineo-content/blob/master/src/tools/ewbd.md), [ewgd ](https://github.com/CLARIAH/ineo-content/blob/master/src/tools/ewgd.md) en [ewld](https://github.com/CLARIAH/ineo-content/blob/master/src/tools/ewld.md) waardoor ik ze niet kan ophalen voor het maken van de templates voor INEO. Het liefst geen dubbele punt in de title gebruiken. 
 
e-WLD: Electronisch woordenboek van de Limburgse dialecten. De :  geeft een key-value pair aan, en dat is niet het geval. Wellicht gaat title: "e-WALD: Electronisch woordenboek van de Achterhoekse en Liemerse dialecten" wel werken ...

**Comment by proycon** [comment]
Is nu gefixed!
